name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: UI Tests
    timeout-minutes: 80
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Set up browser cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/pw-browsers
          key: ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}

      - name: Install dependencies
        run: |
          jlpm install  # Use jlpm instead of yarn, provided by base-setup
          cd ui-tests
          jlpm install

      - name: Build extension
        run: jlpm build

      - name: Launch JupyterLab
        run: |
          jupyter lab --no-browser --port=8888 --NotebookApp.token='' --NotebookApp.password='' &

      - name: Install browser
        run: |
          cd ui-tests
          jlpm playwright install chromium

      - name: Wait for JupyterLab
        run: npx wait-on@7.2.0 http-get://localhost:8888/lab -t 360000

      # Run the Galata tests
      - name: Run UI Tests
        run: |
          cd ui-tests
          jlpm test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ui-tests/test-results
